services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${USER:-www-data}
        uid: ${UID:-33}
    container_name: charge-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    networks:
      - app_network
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
    user: "${UID:-1000}:${GID:-1000}"

  nginx:
    image: nginx:alpine
    container_name: charge-api-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  postgres:
    image: postgres:17-alpine
    container_name: charge-api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-charge_api}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: